GET http://localhost:3000/user/getusers

###
GET http://localhost:3000/user/getusers/jim


###
POST http://localhost:3000/user/createusers
Content-Type: application/json

{
    "username":"jim",
    "password":"halpert",
    "phone":9918284849,
    "recoveryEmail":"jim@sales.com"
}


###
PUT http://localhost:3000/user/updateusers
Content-Type: application/json

{
    "username":"jim",
    "phone":1234567890
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"jim",
    "password":"halpert"
}

###
DELETE http://localhost:3000/user/removeusers/jim

###
DELETE http://localhost:3000/user/deleteallusers


###
POST http://localhost:3000/user/hash/jim