
GET http://localhost:2500/getusers
###

GET http://localhost:2500/getproducts

###

GET http://localhost:2000

###

POST  http://localhost:2000

###

PUT http://localhost:2000

###

DELETE http://localhost:2000